config/routes.rb
Rails.application.routes.draw do
  resources :advisers
  resources :leases
  resources :sales
  resources :pins
  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adviser.rb
class Adviser < ApplicationRecord
	has_many :sales
	has_many :leases
	belongs_to :user
end

app/controllers/advisers_controller.rb
class AdvisersController < ApplicationController
  before_action :set_adviser, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /advisers
  # GET /advisers.json
  def index
    @advisers = Adviser.all
  end

  # GET /advisers/1
  # GET /advisers/1.json
  def show
  end

  # GET /advisers/new
  def new
    @adviser = current_user.advisers.build
  end

  # GET /advisers/1/edit
  def edit
  end

  # POST /advisers
  # POST /advisers.json
  def create
    @adviser = current_user.advisers.build(adviser_params)

    respond_to do |format|
      if @adviser.save
        format.html { redirect_to @adviser, notice: 'Asesor creado correctamente.' }
        format.json { render :show, status: :created, location: @adviser }
      else
        format.html { render :new }
        format.json { render json: @adviser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advisers/1
  # PATCH/PUT /advisers/1.json
  def update
    respond_to do |format|
      if @adviser.update(adviser_params)
        format.html { redirect_to @adviser, notice: 'Asesor actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @adviser }
      else
        format.html { render :edit }
        format.json { render json: @adviser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisers/1
  # DELETE /advisers/1.json
  def destroy
    @adviser.destroy
    respond_to do |format|
      format.html { redirect_to advisers_url, notice: 'Asesor eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adviser
      @adviser = Adviser.find(params[:id])
    end

    def correct_user
      @adviser = current_user.advisers.find_by(id: params[:id])
      redirect_to advisers_path, notice: 'No está autorizado para modificar este asesor' if @adviser.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adviser_params
      params.require(:adviser).permit(:name, :area, :sede)
    end
end

app/helpers/advisers_helper.rb
module AdvisersHelper
end

app/views/advisers/_form.html.erb
<%= form_for(adviser) do |f| %>
  <% if adviser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adviser.errors.count, "error") %> prohibited this adviser from being saved:</h2>

      <ul>
      <% adviser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :Nombre_completo %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :Area %>
    <%= f.select(:area, ['ventas', 'Arrendamientos'], {include_blank: "Selecciona un area..."}, { :class => 'form-control' }) %>
  </div>

  <div class="field form-group">
    <%= f.label :Sede %>
    <%= f.select(:sede, ['Poblado', 'Sabaneta'], {include_blank: "Selecciona la sede..."}, { :class => 'form-control' }) %>
  </div>

  <div class="actions">
    <%= f.submit "enviar", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/advisers/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Editar Asesor</h1>
	</div>

	<div class="panel-body">
		<%= render 'form', adviser: @adviser %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Mostrar', @adviser %> |
		<%= link_to 'Regrasar', advisers_path %>
	</div>
</div>

app/views/advisers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asesores</h1>

<div class="table-responsive">
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Area</th>
        <th>Sede</th>
        <th colspan="3">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @advisers.each do |adviser| %>
        <tr>
          <td><%= adviser.name %></td>
          <td><%= adviser.area %></td>
          <td><%= adviser.sede %></td>
          <td><%= adviser.user.name if adviser.user %></td>
          <td><%= link_to 'Ver', adviser, class: 'btn btn-info btn-xs' %></td>
          <% if adviser.user == current_user %>
            <td><%= link_to 'Editar', edit_adviser_path(adviser), class: 'btn btn-warning btn-xs' %></td>
            <td><%= link_to 'Eliminar', adviser, class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Estas seguro?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<% if user_signed_in? %>
  <%= link_to 'Nuevo Asesor', new_adviser_path, class: 'btn btn-primary' %>
<% end %>

app/views/advisers/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>nuevo Asesor</h1>
	</div>
	
	<div class="panel-body">
		<%= render 'form', adviser: @adviser %>
	</div>
	<div class="panel-footer">
		<%= link_to 'Back', advisers_path %>
	</div>
</div>

app/views/advisers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @adviser.name %>
</p>

<p>
  <strong>Area:</strong>
  <%= @adviser.area %>
</p>

<p>
  <strong>Sede:</strong>
  <%= @adviser.sede %>
</p>

<% if @adviser.user == current_user %>
	<%= link_to 'Edit', edit_adviser_path(@adviser) %> |
<% end %>
<%= link_to 'Back', advisers_path %>