config/routes.rb
Rails.application.routes.draw do
  resources :advisers
  resources :leases
  resources :sales
  resources :pins
  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: 'No está autorizado para modificar este pin' if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_for(pin) do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :descripción %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "enviar", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Editar ping</h1>
	</div>

	<div class="panel-body">
		<%= render 'form', pin: @pin %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Mostrar', @pin %> |
		<%= link_to 'Regrasar', pins_path %>
	</div>
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pins</h1>

<div class="table-responsive">
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Description</th>
        <th>User</th>
        <th colspan="3">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @pins.each do |pin| %>
        <tr>
          <td><%= pin.description %></td>
          <td><%= pin.user.email if pin.user %></td>
          <td><%= link_to 'Ver', pin, class: 'btn btn-info btn-xs' %></td>
          <% if pin.user == current_user %>
            <td><%= link_to 'Editar', edit_pin_path(pin), class: 'btn btn-warning btn-xs' %></td>
            <td><%= link_to 'Eliminar', pin, class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Estas seguro?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<% if user_signed_in? %>
  <%= link_to 'Nuevo Pin', new_pin_path, class: 'btn btn-primary' %>
<% end %>

app/views/pins/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Nuevo ping</h1>
	</div>
	
	<div class="panel-body">
		<%= render 'form', pin: @pin %>
	</div>
	<div class="panel-footer">
		<%= link_to 'Regresar', pins_path %>
	</div>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>
<% if @pin.user == current_user %>
	<%= link_to 'Edit', edit_pin_path(@pin) %> |
<% end %>
<%= link_to 'Back', pins_path %>