config/routes.rb
Rails.application.routes.draw do
  resources :advisers
  resources :leases
  resources :sales
  resources :pins
  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
	belongs_to :adviser
	belongs_to :user

	def display_current_month
  		created_at.strftime('%-b, %Y')
  	end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = current_user.sales.build
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = current_user.sales.build(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Venta creada correctamente.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Venta actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Venta eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    def correct_user
      @sale = current_user.sales.find_by(id: params[:id])
      redirect_to sales_path, notice: 'No está autorizado para modificar esta venta' if @sale.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:adviser_id, :name, :cant)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(sale) do |f| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :Asesor %>
    <%= f.select :adviser_id, Adviser.all.collect { |p| [ p.name, p.id ] }, {include_blank: "Seleccionar asesor..."}, { :class => 'form-control' } %>
  </div>

  <div class="field form-group">
    <%= f.label :Nombre_venta %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :Precio_venta %>
    <%= f.text_field :cant, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "enviar", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Editar ping</h1>
	</div>

	<div class="panel-body">
		<%= render 'form', sale: @sale %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Mostrar', @sale %> |
		<%= link_to 'Regrasar', sales_path %>
	</div>
</div>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ventas</h1>

<div class="table-responsive">
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Asesor</th>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Mes</th>
        <th>Creado por</th>
        <th colspan="3">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @sales.each do |sale| %>
        <tr>
          <td><%= sale.adviser.name %></td>
          <td><%= sale.name %></td>
          <td><%= sale.cant %></td>
          <td><%= sale.display_current_month %></td>
          <td><%= sale.user.email if sale.user %></td>
          <td><%= link_to 'Ver', sale, class: 'btn btn-info btn-xs' %></td>
          <% if sale.user == current_user %>
            <td><%= link_to 'Editar', edit_sale_path(sale), class: 'btn btn-warning btn-xs' %></td>
            <td><%= link_to 'Eliminar', sale, class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Estas seguro?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div><%= bar_chart Sale.group(:adviser_id).sum(:cant) %></div>


<br>
<% if user_signed_in? %>
  <%= link_to 'Nueva venta', new_sale_path, class: 'btn btn-primary' %>
<% end %>

app/views/sales/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Nueva Venta</h1>
	</div>
	
	<div class="panel-body">
		<%= render 'form', sale: @sale %>
	</div>
	<div class="panel-footer">
		<%= link_to 'Volver', sales_path %>
	</div>
</div>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Adviser:</strong>
  <%= @sale.adviser_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @sale.name %>
</p>

<p>
  <strong>Cant:</strong>
  <%= @sale.cant %>
</p>

<% if @sale.user == current_user %>
	<%= link_to 'Edit', edit_sale_path(@sale) %> |
<% end %>
<%= link_to 'Back', sales_path %>